### ISSUE TITLE
_set_last_input_type not working when game is paused

### ISSUE THREAD

**Issue by LinskyUE** [rsubtil/controller_icons#102]
Thanks for the amazing plug-in!

### **Godot version**
4.3 stable

**Issue description**
I'm implementing a pause menu where you can change the user keybingings, and I can't make the icons change when the game is paused, everything works fine when the game is not paused, every relevant node process mode is "ALWAYS", but the plugin dosen't seem to detect device changes when the game is paused.

**Comment by rsubtil** [comment]
Thanks for reporting this bug! I've implemented a fix, can you test it as well please?
https://github.com/rsubtil/controller_icons/archive/refs/heads/cant_stop_wont_stop.zip
