### ISSUE TITLE
No mouse wheel icons

### ISSUE THREAD

**Issue by herrobriam** [rsubtil/controller_icons#109]
![image](https://github.com/user-attachments/assets/12f385a8-707e-4b19-b03c-70f2adc36e08)
![image](https://github.com/user-attachments/assets/5a6b9391-1636-43bf-98f1-08c21b20f3d7)

The mouse wheel doesn't show up as an icon.

**Comment by rsubtil** [comment]
There are currently no mouse wheel icons, as the used pack doesn't have such icons. But, even if new ones are added, the code currently doesn't parse such actions, and this would require more work to support. #108 is planned to fix this properly in the future.
