### ISSUE TITLE
a lot of bugs in godot inspector

### ISSUE THREAD

**Issue by lucasthomaz97** [rsubtil/controller_icons#114]
`res://demo/IconRemapper.gd:29 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://demo/IconRemapper.gd:35 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://demo/IconRemapper.gd:41 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://demo/IconRemapper.gd:47 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://demo/IconRemapper.gd:53 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://demo/IconRemapper.gd:59 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://demo/IconRemapper.gd:65 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://demo/IconRemapper.gd:71 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://demo/IconRemapper.gd:77 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://demo/IconRemapper.gd:83 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://demo/IconRemapper.gd:89 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://demo/IconRemapper.gd:95 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://demo/IconRemapper.gd:101 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://demo/IconRemapper.gd" with error "Parse error". (User)
  res://addons/controller_icons/objects/path_selection/InputActionSelector.gd:68 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/path_selection/InputActionSelector.gd:71 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/path_selection/InputActionSelector.gd:71 - Parse Error: Cannot infer the type of "default_actions" variable because the value doesn't have a set type.
  res://addons/controller_icons/objects/path_selection/InputActionSelector.gd:78 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/controller_icons/objects/path_selection/InputActionSelector.gd" with error "Parse error". (User)
  res://addons/controller_icons/objects/path_selection/SpecificPathSelector.gd:81 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/path_selection/SpecificPathSelector.gd:103 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/controller_icons/objects/path_selection/SpecificPathSelector.gd" with error "Parse error". (User)
  res://addons/controller_icons/objects/Button.gd:19 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Button.gd:21 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Button.gd:26 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Button.gd:26 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Button.gd:31 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Button.gd:31 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Button.gd:34 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Button.gd:39 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Button.gd:40 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Button.gd:47 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Button.gd:47 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Button.gd:49 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/controller_icons/objects/Button.gd" with error "Parse error". (User)
  res://addons/controller_icons/objects/ControllerIconTexture.gd:107 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/ControllerIconTexture.gd:109 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/ControllerIconTexture.gd:114 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/ControllerIconTexture.gd:114 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/ControllerIconTexture.gd:116 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/ControllerIconTexture.gd:116 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/ControllerIconTexture.gd:137 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/ControllerIconTexture.gd:165 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/ControllerIconTexture.gd:166 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/ControllerIconTexture.gd:167 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/ControllerIconTexture.gd:167 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/ControllerIconTexture.gd:168 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/ControllerIconTexture.gd:168 - Parse Error: Cannot infer the type of "event" variable because the value doesn't have a set type.
  res://addons/controller_icons/objects/ControllerIconTexture.gd:169 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/ControllerIconTexture.gd:170 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/ControllerIconTexture.gd:170 - Parse Error: Cannot infer the type of "tex" variable because the value doesn't have a set type.
  res://addons/controller_icons/objects/ControllerIconTexture.gd:182 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/ControllerIconTexture.gd:187 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/ControllerIconTexture.gd:341 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/ControllerIconTexture.gd:344 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/ControllerIconEditorInspector.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/controller_icons/objects/ControllerIconEditorInspector.gd" with error "Parse error". (User)
  res://addons/controller_icons/objects/Sprite3D.gd:19 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Sprite3D.gd:21 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Sprite3D.gd:26 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Sprite3D.gd:26 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Sprite3D.gd:31 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Sprite3D.gd:31 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Sprite3D.gd:34 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Sprite3D.gd:39 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Sprite3D.gd:40 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Sprite3D.gd:48 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Sprite3D.gd:50 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/controller_icons/objects/Sprite3D.gd" with error "Parse error". (User)
  res://addons/controller_icons/objects/Sprite.gd:19 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Sprite.gd:21 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Sprite.gd:26 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Sprite.gd:26 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Sprite.gd:31 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Sprite.gd:31 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Sprite.gd:34 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Sprite.gd:39 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Sprite.gd:40 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Sprite.gd:48 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/Sprite.gd:50 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/controller_icons/objects/Sprite.gd" with error "Parse error". (User)
  res://addons/controller_icons/objects/TextureRect.gd:20 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/TextureRect.gd:22 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/TextureRect.gd:27 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/TextureRect.gd:27 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/TextureRect.gd:32 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/TextureRect.gd:32 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/TextureRect.gd:49 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/TextureRect.gd:55 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/TextureRect.gd:56 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/TextureRect.gd:64 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/objects/TextureRect.gd:66 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/controller_icons/objects/TextureRect.gd" with error "Parse error". (User)
  res://addons/controller_icons/Mapper.gd:41 - Parse Error: Identifier "ControllerIcons" not declared in the current scope.
  res://addons/controller_icons/ControllerIcons.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/controller_icons/ControllerIcons.gd" with error "Compilation failed". (User)
  res://addons/controller_icons/ControllerIcons.gd:34 - Invalid call. Nonexistent function 'new' in base 'GDScript'.`

this just appeared when i installed the addon.
The version is godot 4.3 stable mono official

**Comment by rsubtil** [comment]
When the addon is installed and enabled the first time, the editor must be restarted. This is a limitation from Godot, and not something that can be fixed from the addon's side.

Please confirm if there are no errors after restarting the editor.

**Comment by rsubtil** [comment]
Since there was no response, I'll assume this issue if fixed. Please reopen this if this is still valid.

**Comment by u1967076** [comment]
Hello same kind of errors here.

My system:
Apple M3
Mac oSX 15.3.1 (24D70)
Godot 4.3.stable.official

I tried restart godot and still having errors.

**Comment by JustASquid** [comment]
@rsubtil I'm having this issue as well. After restarting the editor a couple times, the errors changed, There are a few errors:

`res://addons/controller_icons/objects/path_selection/InputActionSelector.gd:97 Parse Error: The method "grab_focus()" overrides a method from native class "Control". This won't be called by the engine and may not work as expected. (Warning treated as error.)`

`res://addons/controller_icons/objects/ControllerIconTexture.gd:240 Parse Error: The variable type is being inferred from a Variant value, so it will be typed as Variant.`

These are actually GDscript warnings which are treated as errors by default (I'm not sure why).

The plugin will load if I enable "Warnings/Exclude Addons" in the GDScript project settings.
However I do think this should be considered an issue in the addon as that setting is not at all obvious.

**Comment by rsubtil** [comment]
Sorry for the late reply @JustASquid, could you open a new issue regarding this? This seems a different topic, since we're talking about warnings on the addon which can be treated as errors on user config.
