### ISSUE TITLE
Getting error `Invalid access to property or key 'input_type_changed' on a base object of type 'Nil'.`

### ISSUE THREAD

**Issue by nubels** [rsubtil/controller_icons#115]
I have have enabled the Controller Icons Plugin in the project settings but when I try to add a Controller Icon Texture,
I get the following error:

`Invalid access to property or key 'input_type_changed' on a base object of type 'Nil'.`

![CleanShot 2024-11-18 at 00 13 24@2x](https://github.com/user-attachments/assets/23eb0ae9-efbf-461f-a542-dc2e277d1beb)
![CleanShot 2024-11-18 at 00 16 25@2x](https://github.com/user-attachments/assets/41fb678f-306e-48ce-b0ac-d1e8eed393c2)

**Comment by rsubtil** [comment]
Can you create a small project replicating this issue that can be shared through here?

Additionally, also confirm if you're not instantiating any singleton/autoload that requires these icons, before the `ControllerIcons` is instantiated; if that's the case, you'll need to move the `ControllerIcons` singleton earlier in the autoload order.

**Comment by nubels** [comment]
> Can you create a small project replicating this issue that can be shared through here?
> 
> Additionally, also confirm if you're not instantiating any singleton/autoload that requires these icons, before the `ControllerIcons` is instantiated; if that's the case, you'll need to move the `ControllerIcons` singleton earlier in the autoload order.

Hey, it was an issue with the autoload order. I was using ControllerIcons in another autoload. Thank you very much!
