### ISSUE TITLE
Fallback event does not always work

### ISSUE THREAD

**Issue by woutercommandeur** [rsubtil/controller_icons#116]
the checking for a fallback event in controllericons.gd (line 285) does not always work

`elif fallback == null and event.device == -1:`

In my case my event.device was -3 not -1. I changed this check locally to event.device < 0: and now it works 100% of the time. No textures were showing up otherwise.

**Comment by rsubtil** [comment]
It seems this change was introduced with https://github.com/godotengine/godot/pull/97707, but subsequently reverted due to this breaking change. In any case, I think it's safe to change the check to `event.device < 0` to make this more resilient.

**Comment by woutercommandeur** [comment]
Sorry I haven't made the pullrequest yet, been busy with a lot of other stuff.
