### ISSUE TITLE
Add mouse scroll wheel button support.

### ISSUE THREAD

**Issue by DataPlusProgram** [rsubtil/controller_icons#118]
For my project I added support for mouse wheel buttons like so:

![image](https://github.com/user-attachments/assets/2e547bf7-8a78-46df-901e-c70323e569dd)

It would be good if this was available by default
If you'd like, you can use the following icons:

| Action                | Image                                                                 |
|-----------------------|----------------------------------------------------------------------|
| Mouse wheel up        | ![image](https://github.com/user-attachments/assets/f61fc2b5-6e84-4ac6-83ce-5bcf1c123d4d) |
| Mouse wheel down      | ![image](https://github.com/user-attachments/assets/ca5cbfeb-80b9-47ad-adc2-44255190c7e4) |
| Middle mouse button   | ![image](https://github.com/user-attachments/assets/46e52834-d790-4bfd-b569-c722ca9f1494) |

Here’s an example implementation:
```
func _convert_mouse_button_to_path(button_index: int):
	match button_index:
		MOUSE_BUTTON_LEFT:
			return "mouse/left"
		MOUSE_BUTTON_RIGHT:
			return "mouse/right"
		MOUSE_BUTTON_MIDDLE:
			return "mouse/middle"
		MOUSE_BUTTON_WHEEL_UP:
			return "mouse/wheelUp"
		MOUSE_BUTTON_WHEEL_DOWN:
			return "mouse/wheelDown"
		_:
			return "mouse/sample"
```
## Further work:

Side mouse buttons could also be added. For example, here’s how they look in Overwatch:

![image](https://github.com/user-attachments/assets/9433dcfe-9afd-4af5-99a4-63eb5a012cf8)

**Comment by rsubtil** [comment]
Thanks for the suggestion! New icons are always going to be a subjective topic, but I think they look nice and fit the aesthetic of the original icon pack. I'll credit your contributed assets, but I do require that new assets are also licensed on the original pack's [CC0](https://creativecommons.org/public-domain/cc0/) license. Is this okay with you?

And yes, the icon pack doesn't currently have mouse side buttons (M4/M5), would be nice to have support for them too. If you were to create icons for these as well, I'd gladly accept them too :slightly_smiling_face:

**Comment by DataPlusProgram** [comment]
Yes that's okay with me. The previous images were missing the transparency layer but these should have them:

![wheelDown](https://github.com/user-attachments/assets/277881fd-a2fe-4824-88a2-eb9a2616bb8e)
![wheelUp](https://github.com/user-attachments/assets/49d7f976-9b89-4a79-a19b-70bd2aba05ae)
![middle](https://github.com/user-attachments/assets/2335f53e-6718-479f-a49a-816e9c417340)
