### ISSUE TITLE
event can be null in "get_matching_event()" in "_custom_input_actions[path]"

### ISSUE THREAD

**Issue by paskausks** [rsubtil/controller_icons#122]
Hello!

First of all, thank you for the plugin, great work!

Initially I started getting multiple of the the following error (which I, weirdly, don't seem to get anymore):

```
res://addons/controller_icons/ControllerIcons.gd:279 - Invalid call. Nonexistent function 'get_class' in base 'Nil'.
```

It looks like in the following code:

```gdscript
func get_matching_event(path: String, input_type: InputType = _last_input_type, controller: int = _last_controller) -> InputEvent:
	var events : Array
	if _custom_input_actions.has(path):
		events = _custom_input_actions[path]
	else:
		events = InputMap.action_get_events(path)
``` 

one of the events in `_custom_input_actions[path]` was null. It happened when moving the mouse after using the controller.

Of course, the error was suppressed in adding a `if not event: continue` guard in the following loop, but that isn't a real solution, and even though I'm not getting the error anymore (i'm not really sure what made it go away, but it wasn't an editor restart), i figured I'd report it, and, I get it again, I have some place to update. 

In the scene I was just using  one controller icon. Both `show mode` and `force type` set to `Controller`. The error appeared after moving the mouse when the controller dpad had been pressed before. A short burst of six or so errors and then nothing. At one point I got it to spam errors on every mouse motion event when i was focused out of the game window while I was moving the mouse around in the editor.

I've just started checking out the plugin, and will update more if I find out more. Since I'm not getting the error at this point, I removed my guard, so if i hit the conditions again, it should reappear.

Godot `v4.3.stable.official [77dcf97d8]` on `Linux 6.8.0-49-generic #49~22.04.1-Ubuntu` using commit `d61c774` of controller_icons (the latest at the time of opening the issue)

**Comment by rsubtil** [comment]
Thanks for reporting this! This is indeed strange, and I haven't managed to replicate anything similar. The closest thing I thought of was to manually modify `project.godot` and set information to null:
```
...
[input]

test_empty={
"deadzone": 0.5,
"events": null
}
```
With this I do get some error spewing due to null content, and I assume similar to what you described (although I don't have any issues when I switch between keyboard/controller). Is it possible this is the issue in your project?

It would be good to know the exact reason, but in any case, it's not a bad idea to do input validation here, especially concerning reading data from project/user files.

**Comment by paskausks** [comment]
Hey!

This is probably project Input Actions configuration specific. I seem to be getting a bunch of these when clicking the "path" widget for the `ControllerTexture`. But I don't remember doing any manual editing in that section. Anyway, I created a godot project with just having copied our Input Actions. I could narrow it down, but I'm in a bit of a rush at work here, but maybe this is enough for you 😅

To repro the bug just:
1) add a `TextureRect`
1) set its texture to a new `ControllerIconTexture`
1) click the "select an Icon path" button.

it should spawn, like, 12 of those errors, which, I guess, might correspond to the entry count in the `project.godot` `[input]` section, I didn't make sure.

[repro.zip](https://github.com/user-attachments/files/18111682/repro.zip)

Hope this helps!

**Comment by rsubtil** [comment]
Thanks for the reproduction project! That seems to be indeed the case, there is a `null` event in your `ui_debug_scene_switcher` action (in the `project.godot` file):
```cfg
...
ui_debug_scene_switcher={
"deadzone": 0.5,
"events": [null, Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":4194332,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)
]
```
Not sure how this happened, but it's likely this occurred from Godot, and is not specific to this addon. In any case, testing for `null` before adding content should fix this and prevent similar issues in the future. Thanks for your help!
