### ISSUE TITLE
4.0.stable rejects ControllerIcons.gd:195

### ISSUE THREAD

**Issue by RegularTetragon** [rsubtil/controller_icons#41]
When grabbing the current version of controller icons from asset lib in godot 4.0.stable, I get the error "Error at (195, 19): Identifier "KEY_SUPER_L" not declared in the current scope." as well as a similar error message for KEY_SUPER_R. When I delete this code that seems to fix the problem.

**Comment by rsubtil** [comment]
This should be fixed by https://github.com/rsubtil/controller_icons/commit/d64fde3ed8dc65b7d1b7bacebb20bf3c294c30dd. I've been waiting to see if there are more errors cropping up before making a release, but it's been some time, so I'll bump it shortly.

**Comment by rsubtil** [comment]
The addon has been updated on the asset lib to 1.1.4, please let me know if this issue still occurs.

**Comment by RegularTetragon** [comment]
It works great now, thank you!
