### ISSUE TITLE
Gamepad icons fail to load.

### ISSUE THREAD

**Issue by TehPurpleOne** [rsubtil/controller_icons#59]
See title. I've installed and uninstalled this plugin many times (Using Godot 3.5.1 Mono). The script seems to be working and no errors appear in the console window, but no matter how hard I try, I am unable to get the gamepad icons to show up.

What's strange is that the icons will update fine when I'm in the editor. But when running the game:
![image](https://github.com/rsubtil/controller_icons/assets/58086292/3cc3a7c0-d3c8-40b5-a661-80a9e0626b30)
![image](https://github.com/rsubtil/controller_icons/assets/58086292/50b7d6a6-3465-4aec-9f48-c38c58245a09)

**Comment by rsubtil** [comment]
Do you mean that keyboard icons work, but when you try any controller input, the icon disappears? If yes, assuming you're using input action paths, what input keys have you added for that particular action?

Also, what is your controller model? It's possible you're using an icon prompt that doesn't exist yet, [check this table to confirm](https://github.com/rsubtil/controller_icons/blob/master/DOCS.md#generic-path-lookup)

**Comment by TehPurpleOne** [comment]
So, after doing some testing, I came to the conclusion that my SaveLoadConfig script was causing the problem. Whenever my game loads the config file, it updates the InputMap. Of course, I forgot about using the Refresh() command. Issue resolved. Sorry for the trouble.
