### ISSUE TITLE
Not respecting joypad fallback for show mode = controller

### ISSUE THREAD

**Issue by SebastianAtWork** [rsubtil/controller_icons#73]
First off: amazing plugin, a huge missing feature of godot.

Even tough I set the Joypad Fallback to something : 
![image](https://github.com/rsubtil/controller_icons/assets/19798013/8f9af7a1-38b5-43ac-a156-d1291a65f7c0)
(doesnt matter if its the default Xbox or ps5)
In Editor, in the Scene, its empty : 
![image](https://github.com/rsubtil/controller_icons/assets/19798013/d028b082-83b2-452d-ab58-7637e629f5a9)
When I plug in a controller, it works fine but it disappears again after I unplug.

**Comment by rsubtil** [comment]
Hi, thank you for the kind words! :heart:

The joypad fallback is only used if controller type detection fails, and in that case it will assume whatever is set in the fallback. If the controller icon does not show up at all, then the issue must be somewhere else.

The `Show Mode` only shows that texture whenever that input method is currently being used. So, with your current settings, it will indeed only show up when a controller is connected/used. If what you want is to force the icon to always show the controller icon even when the keyboard is being used, you need to set the `Force Type` instead.

If that's not the issue, can you please show how that input action is configured in your project?

**Comment by rsubtil** [comment]
Hi, any updates on this? It doesn't seem that there was any real issue here, or do you still believe this is a bug?

**Comment by SebastianAtWork** [comment]
Hi, sorry, I had to stop working on that project because of a new job and stuff. I think Force Type was adequate, but I cant remember if there was still a bug. Sorry.
