### ISSUE TITLE
Changing the path property with code

### ISSUE THREAD

**Issue by MindFlayeR57** [rsubtil/controller_icons#84]
Hi, I'm trying out your plugin and I seem unable to change the path property with code. Is there a method for this? The docs don't seem to mention anything.

**Comment by rsubtil** [comment]
Hi, I believe you're looking for the `path` property on `ControllerIconTexture.gd`. It's usage is documented on the script file as docstrings instead, along with other properties you can modify in code as well:

https://github.com/rsubtil/controller_icons/blob/9564f73819b3469206be2adff53a9d899b010993/addons/controller_icons/objects/ControllerIconTexture.gd#L5-L53
