### ISSUE TITLE
Script broken in godot 4.1.2

### ISSUE THREAD

**Issue by Raptorq1** [rsubtil/controller_icons#86]
Script broken in godot 4.1.2

**Comment by Raptorq1** [comment]
It fixed it self

**Comment by Raptorq1** [comment]
Oh and the icons aren't showing

**Comment by Raptorq1** [comment]
![Screenshot_20240430-074709](https://github.com/rsubtil/controller_icons/assets/106418027/5ede828c-742a-4a1b-a44a-d8215a5460bc)

**Comment by rsubtil** [comment]
Does the icon appear for that specific input action when you use the path picker tool? (the button on the right of the `path` property)

Also, can you show what input events are associated with that action on your project settings?

**Comment by Raptorq1** [comment]
Yes it does but if I test it in game it doesn't show and when I back out to the editor it doesn't show the icon

**Comment by rsubtil** [comment]
Does this issue also occur on a default action, such as `ui_accept`?

And can you reproduce this issue on a completely blank scene as well?

**Comment by Raptorq1** [comment]
It still happens in a blank scene

**Comment by rsubtil** [comment]
> It still happens in a blank scene

Can you test with a default action as well, such as `ui_accept`?

If it works, please try it on a completely new project. It it still occurs, please send that generated project here so I can have a better look on what's going on.

**Comment by rsubtil** [comment]
Since there was no more feedback on this, and there's no MRP to test, I'll close this. Feel free to reopen it if you can create and share a project where this happens reliably.
