### ISSUE TITLE
RichTextLabel and Sprite3D doesn't work in playmode Godot 4.2.2

### ISSUE THREAD

**Issue by fernandoSGameDevelopment** [rsubtil/controller_icons#91]
Outside playmode:
![image](https://github.com/rsubtil/controller_icons/assets/147178218/050f04c5-f5ac-4951-baa9-2b6663616588)

In playmode:
![image](https://github.com/rsubtil/controller_icons/assets/147178218/c48a670f-5e3b-4713-a332-b649a1cccadc)

The debugger pops this single error:
![image](https://github.com/rsubtil/controller_icons/assets/147178218/a9180de1-3f7e-478a-b071-22044a914709)

**Comment by rsubtil** [comment]
`RichTextLabel`'s have this bug which I reported some time ago and has been fixed (https://github.com/godotengine/godot/pull/87587) for 4.3 builds. This hasn't been backported yet to any 4.2 version, so we'll have to wait until it's picked for a new minor release.

`Sprite3D` should not be doing that though; thanks for reporting, I'll have a look :+1:

**Comment by rsubtil** [comment]
@fernandoSGameDevelopment I've pushed a fix that fixes this on my side, could you test this and check if it fixes on yours as well?
https://github.com/rsubtil/controller_icons/archive/refs/heads/fix_sprite3d_icon.zip

**Comment by fernandoSGameDevelopment** [comment]
@rsubtil Yep, it fixed the sprite here as well. Thank you!
When 4.3 or 4.2.3 comes out, I'll test RichTextLabel as well and let you know.

**Comment by fernandoSGameDevelopment** [comment]
@rsubtil 4.3 just released, but `RichTextLabel` seems not to work.
I've tested it on a Windows 11 machine with version 3.1.1 and with the fix_sprite_3d_icon version in this thread.

**Comment by rsubtil** [comment]
Thanks for reporting it promptly. I've also found this issue, and I'll issue a fix shortly :+1:

**Comment by rsubtil** [comment]
@fernandoSGameDevelopment this is fixed on my side, can you confirm if everything works correctly for you as well now?
https://github.com/rsubtil/controller_icons/archive/refs/heads/fix_texture_null_size.zip

**Comment by fernandoSGameDevelopment** [comment]
@rsubtil It now works perfectly! Thanks again for the awesome and fast support.

**Comment by rsubtil** [comment]
Thanks for testing it quickly! There are enough fixes queued so far, so with this one I'll prepare to publish another version.
