### ISSUE TITLE
"Parse Error: Could not find type "ControllerSettings" in the current scope" Godot 4.3 Beta 2

### ISSUE THREAD

**Issue by the-old-one** [rsubtil/controller_icons#95]
It looks like it happens randomly and is randomly getting fixed by a rebuild.
Godot 4.3 Beta 2

![Screenshot 2024-07-03 203734](https://github.com/rsubtil/controller_icons/assets/3480944/fb723871-0f8d-429c-b07f-f70d939d4eb3)

**Comment by rsubtil** [comment]
Hi, are you per chance using the Mono/C# version of Godot?

**Comment by the-old-one** [comment]
> Hi, are you per chance using the Mono/C# version of Godot?

Hi @rsubtil. Yes, It's the C# version.

**Comment by rsubtil** [comment]
Then this is very likely an engine bug. While I haven't found a bug report on the engine yet for it, I've investigated the same problem on another project of mine, and at the time I found issues on other addons such as https://github.com/4d49/godot-console/issues/8, https://github.com/HungryProton/scatter/issues/173 and https://github.com/ramokz/phantom-camera/issues/213, where all of them use a C# version of Godot, which suggests this is an engine bug.

I've attempted to replicate this on a simpler scenario to report this, but haven't managed to do it so far. If you can replicate the issue reliably and on a simple project, I encourage you to report this in Godot (you can also @ me there for any further help I can give)

Sadly there's not much else I can do on my side, so I'll close the issue now, but feel free to continue the discussion if desired :+1:

**Comment by rsubtil** [comment]
@the-old-one there is a new beta ([4.3 beta 3](https://godotengine.org/article/dev-snapshot-godot-4-3-beta-3/)) that has a fix regarding `class_name` that the developers [encouraged to test](https://twitter.com/Akien/status/1806306170140815870), and that maybe can fix this issue. If you can give it a try in your project, please let me know of any results you have.

**Comment by the-old-one** [comment]
@rsubtil It still happens in the beta 3. :( Maybe not as often - I've got it only once today.
It happened after I edited a script for the first time in the session.

**Comment by rsubtil** [comment]
Thanks for testing, then there's not much else to do other than wait for this bug to be fixed eventually.

**Comment by jemballs** [comment]
Hi, I was having this issue also. I would get it multiple times per day. I noticed that the ControllerSettings class file's filename was "Settings.gd", and thinking that (AFAIK) my C# files in my project need to have the same name as the class name, I changed the Settings.gd filename to be ControllerSettings.gd. This issue has not occured even once since I made that change (a few days ago).

I very well could be on a lucky streak 😂 but it might be worth a try @the-old-one.

**Comment by the-old-one** [comment]
@jemballs I'm getting it multiple times a day too. I've found the name difference too but changing the name didn't help. I'm going to try again.
CC @rsubtil

**Comment by jemballs** [comment]
Just like clockwork: it was a lucky streak, and the issue reared its head again! 😂 I will also intermittently poke at this and if I find any sort of solution or work around I'll report back. But other than that, fingers crossed for an engine fix!
