### ISSUE TITLE
Crash in Godot 4.3rc2

### ISSUE THREAD

**Issue by plyoung** [rsubtil/controller_icons#98]
The addon will cause Godot 4.3rc2 to crash on startup of the editor when there are `ControllerIconTexture` resources.

I've tracked it down to `ControllerIconTexture._load_texture_path()` . Commenting out the deferred call seems to "resolve" the issue. I do not know enough about the intention here though so the problem might be somewhere else?

Anyway, this is what I did to get rid of the crash in case it helps identify the real cause.

```
func _load_texture_path():
	# Ensure loading only occurs on the main thread
	#if OS.get_thread_caller_id() != OS.get_main_thread_id():
	#	_load_texture_path_main_thread.call_deferred()
	#else:
	#	_load_texture_path_main_thread()
	_load_texture_path_main_thread()
```

[edit] oh I think it is being looked at here?  https://github.com/rsubtil/controller_icons/pull/96

**Comment by rsubtil** [comment]
#96 was now closed since this was fixed on the engine side; this is very likely the same problem, so I'll close this for now. For anyone else encountering this issue:

> [!note] 
> **This bug was introduced on `v4.3.beta1`, and it is present up until `v4.3.rc2`**; the next RC release should fix this, so **please wait for the next RC release, or use `v4.3.dev6` for now.**
